name: Log Crag Weather

on:
  schedule:
    - cron: '0 */3 * * *'  # Runs every 3 hours
  workflow_dispatch:     # Allows manual triggering

jobs:
  log-weather:
    runs-on: ubuntu-latest
    env:
      OWM_API_KEY: ${{ secrets.OWM_API_KEY }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run weather logger
        run: python src/main.py